---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecloud-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ecloud-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ecloud-exporter
    spec:
      containers:
      - image: zhangrongjie/ecloud_exporter:v0.1.0-beta1
        name: ecloud-exporter
        ports:
        - containerPort: 9199
          name: metrics
          protocol: TCP
        args:
        - "${AccessKey}"
        - "${Secretkey}"
        - "${Pool-Id1}:${productType1}"
        - "${Pool-Id2}:${productType2}"
        env:
        - name: TZ
          value: Asia/Shanghai
        readinessProbe:
          tcpSocket:
            port: 9199
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9199
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ecloud-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: ecloud-exporter
spec:
  ports:
  - name: metrics
    port: 9199
    targetPort: metrics
  selector:
    app.kubernetes.io/name: ecloud-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ecloud-exporter
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - interval: 60s
    port: metrics
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: ecloud-exporter